// <auto-generated />
using System;
using HRTMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRTMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601174709_AddRoleAndStatusTables")]
    partial class AddRoleAndStatusTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRTMS.Models.Feedbacks.Feedback", b =>
                {
                    b.Property<string>("FeedBackId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FeedBackId");

                    b.HasIndex("AccountId");

                    b.HasIndex("RaceId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("HRTMS.Models.Horses.Horse", b =>
                {
                    b.Property<string>("HorseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Health_Cert_Expiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("HourseName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("HorseId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("StatusId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Accounts", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AccountId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StatusId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Jockeys", b =>
                {
                    b.Property<string>("JockeyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ranking")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("JockeyId");

                    b.HasIndex("AccountId");

                    b.HasIndex("StatusId");

                    b.ToTable("Jockeys");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Referee", b =>
                {
                    b.Property<string>("RefereeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefereeLicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefereeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RefereeId");

                    b.HasIndex("AccountId");

                    b.ToTable("Referees");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.RefereePanel", b =>
                {
                    b.Property<string>("RefereePanelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LeadID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Member1ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Member2ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RefereePanelId");

                    b.HasIndex("LeadID");

                    b.HasIndex("Member1ID");

                    b.HasIndex("Member2ID");

                    b.HasIndex("RaceId");

                    b.ToTable("RefereePanels");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Roles", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            IsActive = true,
                            RoleCode = "ADMIN",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            IsActive = true,
                            RoleCode = "REFEREE",
                            RoleName = "Referee"
                        },
                        new
                        {
                            RoleId = 3,
                            IsActive = true,
                            RoleCode = "JOCKEY",
                            RoleName = "Jockey"
                        },
                        new
                        {
                            RoleId = 4,
                            IsActive = true,
                            RoleCode = "HORSE_OWNER",
                            RoleName = "Horse Owner"
                        },
                        new
                        {
                            RoleId = 5,
                            IsActive = true,
                            RoleCode = "SPECTATOR",
                            RoleName = "Spectator"
                        });
                });

            modelBuilder.Entity("HRTMS.Models.Statuss.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.HasIndex("EntityName", "StatusCode")
                        .IsUnique();

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            EntityName = "Account",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "ACTIVE",
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusId = 2,
                            EntityName = "Account",
                            IsActive = true,
                            SortOrder = 2,
                            StatusCode = "LOCKED",
                            StatusName = "Locked"
                        },
                        new
                        {
                            StatusId = 3,
                            EntityName = "Referee",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "ACTIVE",
                            StatusName = "Active"
                        },
                        new
                        {
                            StatusId = 4,
                            EntityName = "Referee",
                            IsActive = true,
                            SortOrder = 2,
                            StatusCode = "SUSPENDED",
                            StatusName = "Suspended"
                        },
                        new
                        {
                            StatusId = 9,
                            EntityName = "Horse",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "INJURED",
                            StatusName = "Injured"
                        },
                        new
                        {
                            StatusId = 10,
                            EntityName = "Horse",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "ELIGIBLE",
                            StatusName = "Eligible"
                        },
                        new
                        {
                            StatusId = 11,
                            EntityName = "Horse",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "SUSPENDED",
                            StatusName = "Suspended"
                        },
                        new
                        {
                            StatusId = 12,
                            EntityName = "Race",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "SCHEDULED",
                            StatusName = "Scheduled"
                        },
                        new
                        {
                            StatusId = 13,
                            EntityName = "Race",
                            IsActive = true,
                            SortOrder = 2,
                            StatusCode = "ONGOING",
                            StatusName = "Ongoing"
                        },
                        new
                        {
                            StatusId = 14,
                            EntityName = "Race",
                            IsActive = true,
                            SortOrder = 3,
                            StatusCode = "COMPLETED",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 15,
                            EntityName = "Race",
                            IsActive = true,
                            SortOrder = 4,
                            StatusCode = "CANCELLED",
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            StatusId = 16,
                            EntityName = "Registration",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "PENDING",
                            StatusName = "Pending"
                        },
                        new
                        {
                            StatusId = 17,
                            EntityName = "Registration",
                            IsActive = true,
                            SortOrder = 2,
                            StatusCode = "APPROVED",
                            StatusName = "Approved"
                        },
                        new
                        {
                            StatusId = 18,
                            EntityName = "Registration",
                            IsActive = true,
                            SortOrder = 3,
                            StatusCode = "REJECTED",
                            StatusName = "Rejected"
                        },
                        new
                        {
                            StatusId = 19,
                            EntityName = "Registration",
                            IsActive = true,
                            SortOrder = 4,
                            StatusCode = "CANCELLED",
                            StatusName = "Cancelled"
                        },
                        new
                        {
                            StatusId = 20,
                            EntityName = "Feedback",
                            IsActive = true,
                            SortOrder = 1,
                            StatusCode = "RESOLVED",
                            StatusName = "Resolved"
                        });
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Races", b =>
                {
                    b.Property<string>("RaceID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Distance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lanes")
                        .HasColumnType("int");

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RaceID");

                    b.HasIndex("StatusId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Registration", b =>
                {
                    b.Property<string>("RegistrationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BackupJockeyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HorseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("JockeyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId");

                    b.HasIndex("BackupJockeyId");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyName");

                    b.HasIndex("RaceId");

                    b.HasIndex("StatusId");

                    b.ToTable("RaceRegistrations");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Rounds", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoundId"));

                    b.Property<string>("RaceID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RoundId");

                    b.HasIndex("RaceID");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Tournaments", b =>
                {
                    b.Property<string>("TournamentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TrackID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TournamentId");

                    b.HasIndex("StatusId");

                    b.HasIndex("TrackID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Tracks", b =>
                {
                    b.Property<string>("TrackId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AvailableDistances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxLanes")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("HRTMS.Models.Feedbacks.Feedback", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Accounts", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.on_board.Races", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HRTMS.Models.Horses.Horse", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Accounts", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Accounts", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Roles", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Jockeys", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Accounts", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.Referee", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Accounts", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("HRTMS.Models.Roles.RefereePanel", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Referee", "Lead")
                        .WithMany()
                        .HasForeignKey("LeadID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Roles.Referee", "Member1")
                        .WithMany()
                        .HasForeignKey("Member1ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Roles.Referee", "Member2")
                        .WithMany()
                        .HasForeignKey("Member2ID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.on_board.Races", "Races")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");

                    b.Navigation("Member1");

                    b.Navigation("Member2");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Races", b =>
                {
                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.on_board.Tournaments", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Registration", b =>
                {
                    b.HasOne("HRTMS.Models.Roles.Jockeys", "BackupJockey")
                        .WithMany()
                        .HasForeignKey("BackupJockeyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HRTMS.Models.Horses.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Roles.Jockeys", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyName")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.on_board.Races", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BackupJockey");

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Race");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Rounds", b =>
                {
                    b.HasOne("HRTMS.Models.on_board.Races", "Race")
                        .WithMany()
                        .HasForeignKey("RaceID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HRTMS.Models.on_board.Tournaments", b =>
                {
                    b.HasOne("HRTMS.Models.Statuss.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HRTMS.Models.on_board.Tracks", "Tracks")
                        .WithMany()
                        .HasForeignKey("TrackID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
