/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SpectatorRouteImport } from './routes/spectator'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RefereeRouteImport } from './routes/referee'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JockeyRouteImport } from './routes/jockey'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectatorScheduleRouteImport } from './routes/spectator.schedule'
import { Route as SpectatorResultsRouteImport } from './routes/spectator.results'
import { Route as SpectatorPredictionsRouteImport } from './routes/spectator.predictions'
import { Route as SpectatorLeaderboardRouteImport } from './routes/spectator.leaderboard'
import { Route as SpectatorDashboardRouteImport } from './routes/spectator.dashboard'
import { Route as SpectatorBettingRouteImport } from './routes/spectator.betting'
import { Route as SpectatorAwardsRouteImport } from './routes/spectator.awards'
import { Route as RefereeViolationsRouteImport } from './routes/referee.violations'
import { Route as RefereeReportsRouteImport } from './routes/referee.reports'
import { Route as RefereeRecordResultRouteImport } from './routes/referee.record-result'
import { Route as RefereePreRaceCheckRouteImport } from './routes/referee.pre-race-check'
import { Route as RefereeDashboardRouteImport } from './routes/referee.dashboard'
import { Route as RefereeAssignedRacesRouteImport } from './routes/referee.assigned-races'
import { Route as OwnerRaceRegistrationRouteImport } from './routes/owner.race-registration'
import { Route as OwnerMyRegistrationsRouteImport } from './routes/owner.my-registrations'
import { Route as OwnerMyHorsesRouteImport } from './routes/owner.my-horses'
import { Route as OwnerJockeyInvitationsRouteImport } from './routes/owner.jockey-invitations'
import { Route as OwnerHorsePerformanceRouteImport } from './routes/owner.horse-performance'
import { Route as OwnerDashboardRouteImport } from './routes/owner.dashboard'
import { Route as OwnerAwardsRouteImport } from './routes/owner.awards'
import { Route as JockeyScheduleRouteImport } from './routes/jockey.schedule'
import { Route as JockeyRaceDetailRouteImport } from './routes/jockey.race-detail'
import { Route as JockeyProfileRouteImport } from './routes/jockey.profile'
import { Route as JockeyPerformanceRouteImport } from './routes/jockey.performance'
import { Route as JockeyInvitationsRouteImport } from './routes/jockey.invitations'
import { Route as JockeyDashboardRouteImport } from './routes/jockey.dashboard'
import { Route as JockeyAwardsRouteImport } from './routes/jockey.awards'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTracksRouteImport } from './routes/admin.tracks'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminRegistrationsRouteImport } from './routes/admin.registrations'
import { Route as AdminRefereesRouteImport } from './routes/admin.referees'
import { Route as AdminRacesRouteImport } from './routes/admin.races'
import { Route as AdminPendingApprovalsRouteImport } from './routes/admin.pending-approvals'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAwardsRouteImport } from './routes/admin.awards'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as SpectatorRaceRaceIdRouteImport } from './routes/spectator.race.$raceId'
import { Route as OwnerHorseHorseIdRouteImport } from './routes/owner.horse.$horseId'
import { Route as AdminRaceControlRaceIdRouteImport } from './routes/admin.race-control.$raceId'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorRoute = SpectatorRouteImport.update({
  id: '/spectator',
  path: '/spectator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RefereeRoute = RefereeRouteImport.update({
  id: '/referee',
  path: '/referee',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JockeyRoute = JockeyRouteImport.update({
  id: '/jockey',
  path: '/jockey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectatorScheduleRoute = SpectatorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorResultsRoute = SpectatorResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorPredictionsRoute = SpectatorPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorLeaderboardRoute = SpectatorLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorDashboardRoute = SpectatorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorBettingRoute = SpectatorBettingRouteImport.update({
  id: '/betting',
  path: '/betting',
  getParentRoute: () => SpectatorRoute,
} as any)
const SpectatorAwardsRoute = SpectatorAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => SpectatorRoute,
} as any)
const RefereeViolationsRoute = RefereeViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => RefereeRoute,
} as any)
const RefereeReportsRoute = RefereeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => RefereeRoute,
} as any)
const RefereeRecordResultRoute = RefereeRecordResultRouteImport.update({
  id: '/record-result',
  path: '/record-result',
  getParentRoute: () => RefereeRoute,
} as any)
const RefereePreRaceCheckRoute = RefereePreRaceCheckRouteImport.update({
  id: '/pre-race-check',
  path: '/pre-race-check',
  getParentRoute: () => RefereeRoute,
} as any)
const RefereeDashboardRoute = RefereeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RefereeRoute,
} as any)
const RefereeAssignedRacesRoute = RefereeAssignedRacesRouteImport.update({
  id: '/assigned-races',
  path: '/assigned-races',
  getParentRoute: () => RefereeRoute,
} as any)
const OwnerRaceRegistrationRoute = OwnerRaceRegistrationRouteImport.update({
  id: '/race-registration',
  path: '/race-registration',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMyRegistrationsRoute = OwnerMyRegistrationsRouteImport.update({
  id: '/my-registrations',
  path: '/my-registrations',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerMyHorsesRoute = OwnerMyHorsesRouteImport.update({
  id: '/my-horses',
  path: '/my-horses',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerJockeyInvitationsRoute = OwnerJockeyInvitationsRouteImport.update({
  id: '/jockey-invitations',
  path: '/jockey-invitations',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHorsePerformanceRoute = OwnerHorsePerformanceRouteImport.update({
  id: '/horse-performance',
  path: '/horse-performance',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAwardsRoute = OwnerAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => OwnerRoute,
} as any)
const JockeyScheduleRoute = JockeyScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyRaceDetailRoute = JockeyRaceDetailRouteImport.update({
  id: '/race-detail',
  path: '/race-detail',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyProfileRoute = JockeyProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyPerformanceRoute = JockeyPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyInvitationsRoute = JockeyInvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyDashboardRoute = JockeyDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => JockeyRoute,
} as any)
const JockeyAwardsRoute = JockeyAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => JockeyRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefereesRoute = AdminRefereesRouteImport.update({
  id: '/referees',
  path: '/referees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRacesRoute = AdminRacesRouteImport.update({
  id: '/races',
  path: '/races',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingApprovalsRoute = AdminPendingApprovalsRouteImport.update({
  id: '/pending-approvals',
  path: '/pending-approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const SpectatorRaceRaceIdRoute = SpectatorRaceRaceIdRouteImport.update({
  id: '/race/$raceId',
  path: '/race/$raceId',
  getParentRoute: () => SpectatorRoute,
} as any)
const OwnerHorseHorseIdRoute = OwnerHorseHorseIdRouteImport.update({
  id: '/horse/$horseId',
  path: '/horse/$horseId',
  getParentRoute: () => OwnerRoute,
} as any)
const AdminRaceControlRaceIdRoute = AdminRaceControlRaceIdRouteImport.update({
  id: '/race-control/$raceId',
  path: '/race-control/$raceId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jockey': typeof JockeyRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRouteWithChildren
  '/signup': typeof SignupRoute
  '/spectator': typeof SpectatorRouteWithChildren
  '/watch': typeof WatchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pending-approvals': typeof AdminPendingApprovalsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/referees': typeof AdminRefereesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/jockey/awards': typeof JockeyAwardsRoute
  '/jockey/dashboard': typeof JockeyDashboardRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/performance': typeof JockeyPerformanceRoute
  '/jockey/profile': typeof JockeyProfileRoute
  '/jockey/race-detail': typeof JockeyRaceDetailRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/awards': typeof OwnerAwardsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/horse-performance': typeof OwnerHorsePerformanceRoute
  '/owner/jockey-invitations': typeof OwnerJockeyInvitationsRoute
  '/owner/my-horses': typeof OwnerMyHorsesRoute
  '/owner/my-registrations': typeof OwnerMyRegistrationsRoute
  '/owner/race-registration': typeof OwnerRaceRegistrationRoute
  '/referee/assigned-races': typeof RefereeAssignedRacesRoute
  '/referee/dashboard': typeof RefereeDashboardRoute
  '/referee/pre-race-check': typeof RefereePreRaceCheckRoute
  '/referee/record-result': typeof RefereeRecordResultRoute
  '/referee/reports': typeof RefereeReportsRoute
  '/referee/violations': typeof RefereeViolationsRoute
  '/spectator/awards': typeof SpectatorAwardsRoute
  '/spectator/betting': typeof SpectatorBettingRoute
  '/spectator/dashboard': typeof SpectatorDashboardRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/spectator/results': typeof SpectatorResultsRoute
  '/spectator/schedule': typeof SpectatorScheduleRoute
  '/admin/race-control/$raceId': typeof AdminRaceControlRaceIdRoute
  '/owner/horse/$horseId': typeof OwnerHorseHorseIdRoute
  '/spectator/race/$raceId': typeof SpectatorRaceRaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jockey': typeof JockeyRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRouteWithChildren
  '/signup': typeof SignupRoute
  '/spectator': typeof SpectatorRouteWithChildren
  '/watch': typeof WatchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pending-approvals': typeof AdminPendingApprovalsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/referees': typeof AdminRefereesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/jockey/awards': typeof JockeyAwardsRoute
  '/jockey/dashboard': typeof JockeyDashboardRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/performance': typeof JockeyPerformanceRoute
  '/jockey/profile': typeof JockeyProfileRoute
  '/jockey/race-detail': typeof JockeyRaceDetailRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/awards': typeof OwnerAwardsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/horse-performance': typeof OwnerHorsePerformanceRoute
  '/owner/jockey-invitations': typeof OwnerJockeyInvitationsRoute
  '/owner/my-horses': typeof OwnerMyHorsesRoute
  '/owner/my-registrations': typeof OwnerMyRegistrationsRoute
  '/owner/race-registration': typeof OwnerRaceRegistrationRoute
  '/referee/assigned-races': typeof RefereeAssignedRacesRoute
  '/referee/dashboard': typeof RefereeDashboardRoute
  '/referee/pre-race-check': typeof RefereePreRaceCheckRoute
  '/referee/record-result': typeof RefereeRecordResultRoute
  '/referee/reports': typeof RefereeReportsRoute
  '/referee/violations': typeof RefereeViolationsRoute
  '/spectator/awards': typeof SpectatorAwardsRoute
  '/spectator/betting': typeof SpectatorBettingRoute
  '/spectator/dashboard': typeof SpectatorDashboardRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/spectator/results': typeof SpectatorResultsRoute
  '/spectator/schedule': typeof SpectatorScheduleRoute
  '/admin/race-control/$raceId': typeof AdminRaceControlRaceIdRoute
  '/owner/horse/$horseId': typeof OwnerHorseHorseIdRoute
  '/spectator/race/$raceId': typeof SpectatorRaceRaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/jockey': typeof JockeyRouteWithChildren
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/referee': typeof RefereeRouteWithChildren
  '/signup': typeof SignupRoute
  '/spectator': typeof SpectatorRouteWithChildren
  '/watch': typeof WatchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/pending-approvals': typeof AdminPendingApprovalsRoute
  '/admin/races': typeof AdminRacesRoute
  '/admin/referees': typeof AdminRefereesRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/jockey/awards': typeof JockeyAwardsRoute
  '/jockey/dashboard': typeof JockeyDashboardRoute
  '/jockey/invitations': typeof JockeyInvitationsRoute
  '/jockey/performance': typeof JockeyPerformanceRoute
  '/jockey/profile': typeof JockeyProfileRoute
  '/jockey/race-detail': typeof JockeyRaceDetailRoute
  '/jockey/schedule': typeof JockeyScheduleRoute
  '/owner/awards': typeof OwnerAwardsRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/owner/horse-performance': typeof OwnerHorsePerformanceRoute
  '/owner/jockey-invitations': typeof OwnerJockeyInvitationsRoute
  '/owner/my-horses': typeof OwnerMyHorsesRoute
  '/owner/my-registrations': typeof OwnerMyRegistrationsRoute
  '/owner/race-registration': typeof OwnerRaceRegistrationRoute
  '/referee/assigned-races': typeof RefereeAssignedRacesRoute
  '/referee/dashboard': typeof RefereeDashboardRoute
  '/referee/pre-race-check': typeof RefereePreRaceCheckRoute
  '/referee/record-result': typeof RefereeRecordResultRoute
  '/referee/reports': typeof RefereeReportsRoute
  '/referee/violations': typeof RefereeViolationsRoute
  '/spectator/awards': typeof SpectatorAwardsRoute
  '/spectator/betting': typeof SpectatorBettingRoute
  '/spectator/dashboard': typeof SpectatorDashboardRoute
  '/spectator/leaderboard': typeof SpectatorLeaderboardRoute
  '/spectator/predictions': typeof SpectatorPredictionsRoute
  '/spectator/results': typeof SpectatorResultsRoute
  '/spectator/schedule': typeof SpectatorScheduleRoute
  '/admin/race-control/$raceId': typeof AdminRaceControlRaceIdRoute
  '/owner/horse/$horseId': typeof OwnerHorseHorseIdRoute
  '/spectator/race/$raceId': typeof SpectatorRaceRaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/jockey'
    | '/login'
    | '/owner'
    | '/profile'
    | '/referee'
    | '/signup'
    | '/spectator'
    | '/watch'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/awards'
    | '/admin/dashboard'
    | '/admin/pending-approvals'
    | '/admin/races'
    | '/admin/referees'
    | '/admin/registrations'
    | '/admin/results'
    | '/admin/tournaments'
    | '/admin/tracks'
    | '/admin/users'
    | '/jockey/awards'
    | '/jockey/dashboard'
    | '/jockey/invitations'
    | '/jockey/performance'
    | '/jockey/profile'
    | '/jockey/race-detail'
    | '/jockey/schedule'
    | '/owner/awards'
    | '/owner/dashboard'
    | '/owner/horse-performance'
    | '/owner/jockey-invitations'
    | '/owner/my-horses'
    | '/owner/my-registrations'
    | '/owner/race-registration'
    | '/referee/assigned-races'
    | '/referee/dashboard'
    | '/referee/pre-race-check'
    | '/referee/record-result'
    | '/referee/reports'
    | '/referee/violations'
    | '/spectator/awards'
    | '/spectator/betting'
    | '/spectator/dashboard'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/spectator/results'
    | '/spectator/schedule'
    | '/admin/race-control/$raceId'
    | '/owner/horse/$horseId'
    | '/spectator/race/$raceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/jockey'
    | '/login'
    | '/owner'
    | '/profile'
    | '/referee'
    | '/signup'
    | '/spectator'
    | '/watch'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/awards'
    | '/admin/dashboard'
    | '/admin/pending-approvals'
    | '/admin/races'
    | '/admin/referees'
    | '/admin/registrations'
    | '/admin/results'
    | '/admin/tournaments'
    | '/admin/tracks'
    | '/admin/users'
    | '/jockey/awards'
    | '/jockey/dashboard'
    | '/jockey/invitations'
    | '/jockey/performance'
    | '/jockey/profile'
    | '/jockey/race-detail'
    | '/jockey/schedule'
    | '/owner/awards'
    | '/owner/dashboard'
    | '/owner/horse-performance'
    | '/owner/jockey-invitations'
    | '/owner/my-horses'
    | '/owner/my-registrations'
    | '/owner/race-registration'
    | '/referee/assigned-races'
    | '/referee/dashboard'
    | '/referee/pre-race-check'
    | '/referee/record-result'
    | '/referee/reports'
    | '/referee/violations'
    | '/spectator/awards'
    | '/spectator/betting'
    | '/spectator/dashboard'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/spectator/results'
    | '/spectator/schedule'
    | '/admin/race-control/$raceId'
    | '/owner/horse/$horseId'
    | '/spectator/race/$raceId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/jockey'
    | '/login'
    | '/owner'
    | '/profile'
    | '/referee'
    | '/signup'
    | '/spectator'
    | '/watch'
    | '/admin/analytics'
    | '/admin/audit-log'
    | '/admin/awards'
    | '/admin/dashboard'
    | '/admin/pending-approvals'
    | '/admin/races'
    | '/admin/referees'
    | '/admin/registrations'
    | '/admin/results'
    | '/admin/tournaments'
    | '/admin/tracks'
    | '/admin/users'
    | '/jockey/awards'
    | '/jockey/dashboard'
    | '/jockey/invitations'
    | '/jockey/performance'
    | '/jockey/profile'
    | '/jockey/race-detail'
    | '/jockey/schedule'
    | '/owner/awards'
    | '/owner/dashboard'
    | '/owner/horse-performance'
    | '/owner/jockey-invitations'
    | '/owner/my-horses'
    | '/owner/my-registrations'
    | '/owner/race-registration'
    | '/referee/assigned-races'
    | '/referee/dashboard'
    | '/referee/pre-race-check'
    | '/referee/record-result'
    | '/referee/reports'
    | '/referee/violations'
    | '/spectator/awards'
    | '/spectator/betting'
    | '/spectator/dashboard'
    | '/spectator/leaderboard'
    | '/spectator/predictions'
    | '/spectator/results'
    | '/spectator/schedule'
    | '/admin/race-control/$raceId'
    | '/owner/horse/$horseId'
    | '/spectator/race/$raceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  JockeyRoute: typeof JockeyRouteWithChildren
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RefereeRoute: typeof RefereeRouteWithChildren
  SignupRoute: typeof SignupRoute
  SpectatorRoute: typeof SpectatorRouteWithChildren
  WatchRoute: typeof WatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator': {
      id: '/spectator'
      path: '/spectator'
      fullPath: '/spectator'
      preLoaderRoute: typeof SpectatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referee': {
      id: '/referee'
      path: '/referee'
      fullPath: '/referee'
      preLoaderRoute: typeof RefereeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jockey': {
      id: '/jockey'
      path: '/jockey'
      fullPath: '/jockey'
      preLoaderRoute: typeof JockeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectator/schedule': {
      id: '/spectator/schedule'
      path: '/schedule'
      fullPath: '/spectator/schedule'
      preLoaderRoute: typeof SpectatorScheduleRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/results': {
      id: '/spectator/results'
      path: '/results'
      fullPath: '/spectator/results'
      preLoaderRoute: typeof SpectatorResultsRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/predictions': {
      id: '/spectator/predictions'
      path: '/predictions'
      fullPath: '/spectator/predictions'
      preLoaderRoute: typeof SpectatorPredictionsRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/leaderboard': {
      id: '/spectator/leaderboard'
      path: '/leaderboard'
      fullPath: '/spectator/leaderboard'
      preLoaderRoute: typeof SpectatorLeaderboardRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/dashboard': {
      id: '/spectator/dashboard'
      path: '/dashboard'
      fullPath: '/spectator/dashboard'
      preLoaderRoute: typeof SpectatorDashboardRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/betting': {
      id: '/spectator/betting'
      path: '/betting'
      fullPath: '/spectator/betting'
      preLoaderRoute: typeof SpectatorBettingRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/spectator/awards': {
      id: '/spectator/awards'
      path: '/awards'
      fullPath: '/spectator/awards'
      preLoaderRoute: typeof SpectatorAwardsRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/referee/violations': {
      id: '/referee/violations'
      path: '/violations'
      fullPath: '/referee/violations'
      preLoaderRoute: typeof RefereeViolationsRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/referee/reports': {
      id: '/referee/reports'
      path: '/reports'
      fullPath: '/referee/reports'
      preLoaderRoute: typeof RefereeReportsRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/referee/record-result': {
      id: '/referee/record-result'
      path: '/record-result'
      fullPath: '/referee/record-result'
      preLoaderRoute: typeof RefereeRecordResultRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/referee/pre-race-check': {
      id: '/referee/pre-race-check'
      path: '/pre-race-check'
      fullPath: '/referee/pre-race-check'
      preLoaderRoute: typeof RefereePreRaceCheckRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/referee/dashboard': {
      id: '/referee/dashboard'
      path: '/dashboard'
      fullPath: '/referee/dashboard'
      preLoaderRoute: typeof RefereeDashboardRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/referee/assigned-races': {
      id: '/referee/assigned-races'
      path: '/assigned-races'
      fullPath: '/referee/assigned-races'
      preLoaderRoute: typeof RefereeAssignedRacesRouteImport
      parentRoute: typeof RefereeRoute
    }
    '/owner/race-registration': {
      id: '/owner/race-registration'
      path: '/race-registration'
      fullPath: '/owner/race-registration'
      preLoaderRoute: typeof OwnerRaceRegistrationRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/my-registrations': {
      id: '/owner/my-registrations'
      path: '/my-registrations'
      fullPath: '/owner/my-registrations'
      preLoaderRoute: typeof OwnerMyRegistrationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/my-horses': {
      id: '/owner/my-horses'
      path: '/my-horses'
      fullPath: '/owner/my-horses'
      preLoaderRoute: typeof OwnerMyHorsesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/jockey-invitations': {
      id: '/owner/jockey-invitations'
      path: '/jockey-invitations'
      fullPath: '/owner/jockey-invitations'
      preLoaderRoute: typeof OwnerJockeyInvitationsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/horse-performance': {
      id: '/owner/horse-performance'
      path: '/horse-performance'
      fullPath: '/owner/horse-performance'
      preLoaderRoute: typeof OwnerHorsePerformanceRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/awards': {
      id: '/owner/awards'
      path: '/awards'
      fullPath: '/owner/awards'
      preLoaderRoute: typeof OwnerAwardsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/jockey/schedule': {
      id: '/jockey/schedule'
      path: '/schedule'
      fullPath: '/jockey/schedule'
      preLoaderRoute: typeof JockeyScheduleRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/race-detail': {
      id: '/jockey/race-detail'
      path: '/race-detail'
      fullPath: '/jockey/race-detail'
      preLoaderRoute: typeof JockeyRaceDetailRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/profile': {
      id: '/jockey/profile'
      path: '/profile'
      fullPath: '/jockey/profile'
      preLoaderRoute: typeof JockeyProfileRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/performance': {
      id: '/jockey/performance'
      path: '/performance'
      fullPath: '/jockey/performance'
      preLoaderRoute: typeof JockeyPerformanceRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/invitations': {
      id: '/jockey/invitations'
      path: '/invitations'
      fullPath: '/jockey/invitations'
      preLoaderRoute: typeof JockeyInvitationsRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/dashboard': {
      id: '/jockey/dashboard'
      path: '/dashboard'
      fullPath: '/jockey/dashboard'
      preLoaderRoute: typeof JockeyDashboardRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/jockey/awards': {
      id: '/jockey/awards'
      path: '/awards'
      fullPath: '/jockey/awards'
      preLoaderRoute: typeof JockeyAwardsRouteImport
      parentRoute: typeof JockeyRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/referees': {
      id: '/admin/referees'
      path: '/referees'
      fullPath: '/admin/referees'
      preLoaderRoute: typeof AdminRefereesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/races': {
      id: '/admin/races'
      path: '/races'
      fullPath: '/admin/races'
      preLoaderRoute: typeof AdminRacesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pending-approvals': {
      id: '/admin/pending-approvals'
      path: '/pending-approvals'
      fullPath: '/admin/pending-approvals'
      preLoaderRoute: typeof AdminPendingApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/spectator/race/$raceId': {
      id: '/spectator/race/$raceId'
      path: '/race/$raceId'
      fullPath: '/spectator/race/$raceId'
      preLoaderRoute: typeof SpectatorRaceRaceIdRouteImport
      parentRoute: typeof SpectatorRoute
    }
    '/owner/horse/$horseId': {
      id: '/owner/horse/$horseId'
      path: '/horse/$horseId'
      fullPath: '/owner/horse/$horseId'
      preLoaderRoute: typeof OwnerHorseHorseIdRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/admin/race-control/$raceId': {
      id: '/admin/race-control/$raceId'
      path: '/race-control/$raceId'
      fullPath: '/admin/race-control/$raceId'
      preLoaderRoute: typeof AdminRaceControlRaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPendingApprovalsRoute: typeof AdminPendingApprovalsRoute
  AdminRacesRoute: typeof AdminRacesRoute
  AdminRefereesRoute: typeof AdminRefereesRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminRaceControlRaceIdRoute: typeof AdminRaceControlRaceIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPendingApprovalsRoute: AdminPendingApprovalsRoute,
  AdminRacesRoute: AdminRacesRoute,
  AdminRefereesRoute: AdminRefereesRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminRaceControlRaceIdRoute: AdminRaceControlRaceIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface JockeyRouteChildren {
  JockeyAwardsRoute: typeof JockeyAwardsRoute
  JockeyDashboardRoute: typeof JockeyDashboardRoute
  JockeyInvitationsRoute: typeof JockeyInvitationsRoute
  JockeyPerformanceRoute: typeof JockeyPerformanceRoute
  JockeyProfileRoute: typeof JockeyProfileRoute
  JockeyRaceDetailRoute: typeof JockeyRaceDetailRoute
  JockeyScheduleRoute: typeof JockeyScheduleRoute
}

const JockeyRouteChildren: JockeyRouteChildren = {
  JockeyAwardsRoute: JockeyAwardsRoute,
  JockeyDashboardRoute: JockeyDashboardRoute,
  JockeyInvitationsRoute: JockeyInvitationsRoute,
  JockeyPerformanceRoute: JockeyPerformanceRoute,
  JockeyProfileRoute: JockeyProfileRoute,
  JockeyRaceDetailRoute: JockeyRaceDetailRoute,
  JockeyScheduleRoute: JockeyScheduleRoute,
}

const JockeyRouteWithChildren =
  JockeyRoute._addFileChildren(JockeyRouteChildren)

interface OwnerRouteChildren {
  OwnerAwardsRoute: typeof OwnerAwardsRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerHorsePerformanceRoute: typeof OwnerHorsePerformanceRoute
  OwnerJockeyInvitationsRoute: typeof OwnerJockeyInvitationsRoute
  OwnerMyHorsesRoute: typeof OwnerMyHorsesRoute
  OwnerMyRegistrationsRoute: typeof OwnerMyRegistrationsRoute
  OwnerRaceRegistrationRoute: typeof OwnerRaceRegistrationRoute
  OwnerHorseHorseIdRoute: typeof OwnerHorseHorseIdRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAwardsRoute: OwnerAwardsRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerHorsePerformanceRoute: OwnerHorsePerformanceRoute,
  OwnerJockeyInvitationsRoute: OwnerJockeyInvitationsRoute,
  OwnerMyHorsesRoute: OwnerMyHorsesRoute,
  OwnerMyRegistrationsRoute: OwnerMyRegistrationsRoute,
  OwnerRaceRegistrationRoute: OwnerRaceRegistrationRoute,
  OwnerHorseHorseIdRoute: OwnerHorseHorseIdRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface RefereeRouteChildren {
  RefereeAssignedRacesRoute: typeof RefereeAssignedRacesRoute
  RefereeDashboardRoute: typeof RefereeDashboardRoute
  RefereePreRaceCheckRoute: typeof RefereePreRaceCheckRoute
  RefereeRecordResultRoute: typeof RefereeRecordResultRoute
  RefereeReportsRoute: typeof RefereeReportsRoute
  RefereeViolationsRoute: typeof RefereeViolationsRoute
}

const RefereeRouteChildren: RefereeRouteChildren = {
  RefereeAssignedRacesRoute: RefereeAssignedRacesRoute,
  RefereeDashboardRoute: RefereeDashboardRoute,
  RefereePreRaceCheckRoute: RefereePreRaceCheckRoute,
  RefereeRecordResultRoute: RefereeRecordResultRoute,
  RefereeReportsRoute: RefereeReportsRoute,
  RefereeViolationsRoute: RefereeViolationsRoute,
}

const RefereeRouteWithChildren =
  RefereeRoute._addFileChildren(RefereeRouteChildren)

interface SpectatorRouteChildren {
  SpectatorAwardsRoute: typeof SpectatorAwardsRoute
  SpectatorBettingRoute: typeof SpectatorBettingRoute
  SpectatorDashboardRoute: typeof SpectatorDashboardRoute
  SpectatorLeaderboardRoute: typeof SpectatorLeaderboardRoute
  SpectatorPredictionsRoute: typeof SpectatorPredictionsRoute
  SpectatorResultsRoute: typeof SpectatorResultsRoute
  SpectatorScheduleRoute: typeof SpectatorScheduleRoute
  SpectatorRaceRaceIdRoute: typeof SpectatorRaceRaceIdRoute
}

const SpectatorRouteChildren: SpectatorRouteChildren = {
  SpectatorAwardsRoute: SpectatorAwardsRoute,
  SpectatorBettingRoute: SpectatorBettingRoute,
  SpectatorDashboardRoute: SpectatorDashboardRoute,
  SpectatorLeaderboardRoute: SpectatorLeaderboardRoute,
  SpectatorPredictionsRoute: SpectatorPredictionsRoute,
  SpectatorResultsRoute: SpectatorResultsRoute,
  SpectatorScheduleRoute: SpectatorScheduleRoute,
  SpectatorRaceRaceIdRoute: SpectatorRaceRaceIdRoute,
}

const SpectatorRouteWithChildren = SpectatorRoute._addFileChildren(
  SpectatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  JockeyRoute: JockeyRouteWithChildren,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RefereeRoute: RefereeRouteWithChildren,
  SignupRoute: SignupRoute,
  SpectatorRoute: SpectatorRouteWithChildren,
  WatchRoute: WatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
